scan_id: 00000000-0000-0000-0000-000000000000
seed_tag: cloud_connector
delete_stale_seeds: true
aws:
  enabled: true
  api_key_secret: asm-cloud-connector/api-key
  default_region: eu-west-2
  services:
    check_ec2: true
    check_eip: true
    check_elb: true
    check_s3: true
    check_acm: true
    check_route53: true
    check_cloudfront: true
    check_api_gateway: true
    check_api_gateway_v2: true
    check_eks: true
    check_rds: true
    check_opensearch: true
    check_lambda: true
azure:
  enabled: false
  services:
    check_public_ip_addresses: true
    check_application_gateways: true
    check_application_gateway_certificates: true
    check_front_door_classic: true
    check_front_door_afd: true
    check_traffic_manager: true
    check_dns_zones: true
    check_dns_records: true
    check_storage_static_websites: true
    check_cdn_endpoints: true
    check_app_services: true
    check_sql_servers: true
    check_cosmos_db: true
    check_redis_cache: true
gcp:
  enabled: false
  projects:
    - projects/123456
  services:
    check_dns_resource_record_set: true
    check_dns_managed_zone: true
    check_compute_instance: true
    check_compute_address: true
    check_storage_bucket: true
    check_cloud_function: true
    check_run_service: true
    check_run_domain_mapping: true
    check_api_gateway: true
    check_sql_instance: true
    check_compute_forwarding_rule: true
    check_compute_global_forwarding_rule: true
    check_compute_url_map: true
    check_app_engine_service: true
    check_gke_cluster: true
    check_certificates: true
